defaults: &device_defaults
  ip: 66.129.235.201
  username: jcluser
  password: Juniper!1

devices:
  - name: vmx1
    <<: *device_defaults
    ssh_port: 48009
    netconf_port: 48007
    port: 48008
    router-id: 1.1.1.1
    interfaces:
      - name: ge-0/0/0
        ip: 100.10.1.1/24
        ospf_area: 0.0.0.0
      - name: ge-0/0/1
        ip: 100.10.8.1/24
        ospf_area: 0.0.0.0
      - name: ge-0/0/2
        ip: 100.10.7.1/24
        ospf_area: 0.0.0.0
      - name: ge-0/0/3
        ip: 100.10.6.1/24
        ospf_area: 0.0.0.1

  - name: vmx2
    <<: *device_defaults
    ssh_port: 48012
    netconf_port: 48010
    port: 48011

    router-id: 1.1.1.2
    interfaces:
      - name: ge-0/0/0
        ip: 100.10.1.2/24
        ospf_area: 0.0.0.0
      - name: ge-0/0/1
        ip: 100.10.9.1/24
        ospf_area: 0.0.0.0
      - name: ge-0/0/2
        ip: 100.10.10.1/24
        ospf_area: 0.0.0.0
      - name: ge-0/0/3
        ip: 100.10.2.1/24
        ospf_area: 0.0.0.2

  - name: vmx3
    <<: *device_defaults
    ssh_port: 48015
    netconf_port: 48013
    port: 48014
    router-id: 1.1.1.3
    interfaces:
      - name: ge-0/0/0
        ip: 100.10.4.2/24
        ospf_area: 0.0.0.0
      - name: ge-0/0/1
        ip: 100.10.9.2/24
        ospf_area: 0.0.0.0
      - name: ge-0/0/2
        ip: 100.10.7.2/24
        ospf_area: 0.0.0.0
      - name: ge-0/0/4
        ip: 100.10.5.1/24
        ospf_area: 0.0.0.1

  - name: vmx4
    <<: *device_defaults
    ssh_port: 48018
    netconf_port: 48016
    port: 48017
    router-id: 1.1.1.4
    interfaces:
      - name: ge-0/0/0
        ip: 100.10.4.1/24
        ospf_area: 0.0.0.0
      - name: ge-0/0/1
        ip: 100.10.8.2/24
        ospf_area: 0.0.0.0
      - name: ge-0/0/2
        ip: 100.10.10.2/24
        ospf_area: 0.0.0.0
      - name: ge-0/0/4
        ip: 100.10.3.2/24
        ospf_area: 0.0.0.2

  - name: vmx5
    <<: *device_defaults
    ssh_port: 48021
    netconf_port: 48019
    port: 48020
    router-id: 1.1.1.5
    interfaces:
      - name: ge-0/0/3
        ip: 100.10.6.1/24
        ospf_area: 0.0.0.1
      - name: ge-0/0/4
        ip: 100.10.5.2/24
        ospf_area: 0.0.0.1

  - name: vmx6
    <<: *device_defaults
    ssh_port: 48024
    netconf_port: 48022
    port: 48023
    router-id: 1.1.1.4
    interfaces:
      - name: ge-0/0/3
        ip: 100.10.2.2/24
        ospf_area: 0.0.0.2
      - name: ge-0/0/4
        ip: 100.10.3.1/24
        ospf_area: 0.0.0.2